### ISSUE TITLE
YAML Configuration Support

### ISSUE THREAD

**Issue by butschster** [butschster/context-generator#59]
This RFC proposes adding YAML configuration format support to the Context Generator tool alongside the existing JSON and PHP array formats. This enhancement would provide users with more flexibility and a more readable configuration syntax, particularly for complex context generation scenarios.

## Background

The Context Generator currently supports two configuration formats:
1. JSON (`context.json`)
2. PHP arrays (`context.php`)

While these formats are functional, YAML offers several advantages in terms of readability and maintainability, especially for complex configurations with nested structures and long text blocks.

#### 1. Dependencies

Add Symfony YAML component as a dependency:

```bash
composer require symfony/yaml
```

#### 2. New Components

Add the following new classes:

- `YamlConfigDocumentsLoader` - Loads configuration from YAML files
- Optional: `YamlParser` if custom YAML parsing is needed

#### 3. Command Updates

Update `GenerateCommand` to support YAML file extensions and to use the appropriate loader based on file extension.

#### 4. Documentation

Update documentation to include YAML configuration examples and usage instructions.

## Sequence Diagram

```mermaid
sequenceDiagram
    participant User
    participant GenerateCommand
    participant CompositeDocumentsLoader
    participant YamlConfigDocumentsLoader
    participant SymfonyYamlParser
    participant ConfigParser
    participant DocumentRegistry

    User->>GenerateCommand: Execute with context.yaml
    GenerateCommand->>CompositeDocumentsLoader: load()
    CompositeDocumentsLoader->>YamlConfigDocumentsLoader: isSupported()
    YamlConfigDocumentsLoader-->>CompositeDocumentsLoader: true
    CompositeDocumentsLoader->>YamlConfigDocumentsLoader: load()
    YamlConfigDocumentsLoader->>SymfonyYamlParser: parse()
    SymfonyYamlParser-->>YamlConfigDocumentsLoader: parsed YAML array
    YamlConfigDocumentsLoader->>ConfigParser: parse()
    ConfigParser-->>YamlConfigDocumentsLoader: parsed configuration
    YamlConfigDocumentsLoader->>DocumentRegistry: create registry
    DocumentRegistry-->>YamlConfigDocumentsLoader: document registry
    YamlConfigDocumentsLoader-->>CompositeDocumentsLoader: document registry
    CompositeDocumentsLoader-->>GenerateCommand: document registry
    GenerateCommand->>User: Generated context files
```

### 1. Improved Readability and Maintainability

YAML's syntax is more readable than JSON, especially for:
- Complex nested structures
- Multi-line strings
- Comments (which JSON doesn't support natively)

Example of the same configuration in JSON vs YAML:

**JSON:**
```json
{
  "documents": [
    {
      "description": "API Documentation",
      "outputPath": "docs/api.md",
      "sources": [
        {
          "type": "text",
          "description": "Header",
          "content": "# API Documentation\n\nThis document provides an overview of the API."
        }
      ]
    }
  ]
}
```

**YAML:**
```yaml
documents:
  - description: API Documentation
    outputPath: docs/api.md
    sources:
      - type: text
        description: Header
        content: |
          # API Documentation
          
          This document provides an overview of the API.
```

### 2. Native Comment Support

YAML allows for comments within the configuration file, which can be valuable for:
- Documenting complex configurations
- Temporarily disabling sections
- Adding contextual notes for team members

```yaml
documents:
  - description: API Documentation
    outputPath: docs/api.md
    # This document combines multiple API source types
    sources:
      # Main header with project information
      - type: text
        description: Header
        content: |
          # API Documentation
          
          This document provides an overview of the API.
```

### 3. Multi-line String Handling

YAML's block scalar styles (`|` and `>`) provide elegant solutions for multi-line text, which is common in Context Generator for:
- Descriptive text blocks
- Code snippets
- Instructions and notes

### 4. Industry Standard

YAML is widely used in modern development tools and platforms:
- Kubernetes configurations
- GitHub Actions workflows
- Docker Compose files
- CI/CD pipeline configurations
- Static site generators

Supporting YAML aligns Context Generator with industry practices and user expectations.

### 5. Easier Integration with Other Tools

Many tools can generate or modify YAML, making it easier to:
- Programmatically generate Context Generator configurations
- Integrate with templating systems
- Work with configuration management tools
